
development:
  adapter: postgresql
  encoding: unicode
  database: parliamentary-questions_dev
  host: localhost
  pool: 10


test:
  adapter: postgresql
  encoding: unicode
  database: parliamentary-questions_test
  host: localhost
  pool: 10

production:
  host: <%= ENV['PQ_DB_HOST'] %>
  encoding: unicode
  username: <%= ENV['PQ_DB_USERNAME'] %>
  password: <%= ENV['PQ_DB_PASSWORD'] %>
  database: parliamentary-questions
  pool: 15
